import {
    Blog,
    BlogBox,
    BlogBoxReg,
    BlogContainer,
    BlogSection
} from '@/components/blog'
import { Container } from '@/components/display'
import TextComponent from '@/components/text'
import handleLink from '@/constants/handleBlogLink'
import { Image } from '@nextui-org/react'
import Link from 'next/link'
import { BiCircle } from 'react-icons/bi'
import { BsFillCircleFill } from 'react-icons/bs'

export default function InstagramPostGenerator() {
    const keyItems: string[] = [
        `<green-300>Keyword-Based Content Generation:</green-300> Simply input the keywords that define the focus of your post, and the tool will generate three distinct Instagram posts. Each post includes a catchy caption, relevant hashtags, and engaging emojis, all formatted for quick and easy insertion into Instagram.`,
        `<green-300>Engaging Captions:</green-300> The captions generated by this tool are designed to grab attention, spark curiosity, and encourage interaction. They align with current trends, making your posts more likely to go viral.`,
        `<green-300>Relevant Hashtags:</green-300> Hashtags are crucial for discoverability on Instagram. This tool selects niche-specific and trending hashtags that boost your post’s visibility, helping you reach a broader audience.`,
        `<green-300>Emojis for Impact:</green-300> The inclusion of emojis in the captions adds a visual element that enhances the emotional appeal of your posts, making them more relatable and shareable.`
    ]

    const whatsItems: string[] = [
        '<semi><yellow-400>Input Keywords:</yellow-400></semi> Start by entering the keywords that represent the theme or message of your post. These keywords can be related to your brand, product, lifestyle, or any other topic you wish to highlight.',
        '<semi><yellow-400>Receive 3 Posts:</yellow-400></semi> The tool then generates three different Instagram posts, each with a unique caption, relevant hashtags, and strategically placed emojis. The posts are designed to be diverse yet aligned with your overall messaging strategy.',
        '<semi><yellow-400>Copy and Paste</yellow-400></semi> Once the posts are generated, you can easily copy and paste them directly into your Instagram feed, saving you time and effort while ensuring your content is engaging and on-trend.'
    ]

    return (
        <Blog dir="ltr">
            <BlogSection className="max-sm:text-center">
                <p>
                    In today's fast-paced digital world, creating engaging
                    content for Instagram is essential to capture attention and
                    drive interaction. However, coming up with fresh and
                    appealing posts regularly can be a challenge. The Instagram
                    Post Generator is an AI-powered tool designed to help you
                    craft compelling and viral Instagram posts with ease. By
                    leveraging the power of AI, this tool generates creative and
                    trend-aligned posts based on your specified keywords,
                    ensuring that your content not only stands out but also
                    resonates with your target audience.
                </p>
            </BlogSection>

            <BlogSection className="mt-5">
                <BlogBoxReg title="What Does This Tool Offer?">
                    <TextComponent
                        message={`The <bold>Instagram Post Generator</bold> simplifies the content creation process by providing three ready-to-use Instagram posts tailored to your needs. Whether you’re promoting a product, sharing a lifestyle update, or engaging with your followers on a trending topic, this tool ensures that your posts are optimized for maximum impact. Here's how it works:`}
                    />
                </BlogBoxReg>
            </BlogSection>

            <BlogSection>
                <BlogBoxReg title="Key Features">
                    {keyItems.map((item, index) => {
                        return (
                            <BlogContainer
                                key={index}
                                className="flex justify-center mt-3">
                                <Container className="mr-2 mt-[3px] ">
                                    <BiCircle className="text-sm" />
                                </Container>
                                <TextComponent message={item} />
                            </BlogContainer>
                        )
                    })}

                    <BlogContainer className="mt-5">
                        <Image
                            isBlurred
                            isZoomed
                            src="/instagram.png"
                            className="w-[500px] h-[500px] max-sm:w-[300px] max-sm:h-[300px]"
                        />
                    </BlogContainer>
                </BlogBoxReg>
            </BlogSection>

            <BlogSection>
                <BlogBoxReg title="How It Works?" wrapperClassName="mt-9">
                    {whatsItems.map((item, index) => {
                        return (
                            <BlogContainer
                                key={index}
                                className="flex justify-center">
                                <Container className="mr-2 mt-[3px] ">
                                    <BsFillCircleFill
                                        size={7}
                                        className="mt-1"
                                    />
                                </Container>
                                <TextComponent message={item} />
                            </BlogContainer>
                        )
                    })}
                </BlogBoxReg>
            </BlogSection>

            <BlogSection>
                <BlogBoxReg title="Why Use This Tool?">
                    <Container flexDecoration="col">
                        <TextComponent
                            message={`The <bold><red-200>Instagram Post Generator</red-200></bold> is perfect for businesses,
                        influencers, and social media managers looking to
                        maintain a consistent and appealing presence on
                        Instagram. By automating the content creation process,
                        this tool allows you to focus on other important aspects
                        of your social media strategy, such as interacting with
                        your audience and analyzing performance metrics.`}
                        />

                        <TextComponent
                            className="mt-5"
                            message={`Whether you're looking to boost your brand’s visibility,
                    engage more effectively with your followers, or simply keep
                    your Instagram feed fresh and vibrant, the <bold><red-200>Instagram Post Generator</red-200></bold> offers a quick, reliable, and creative solution.`}
                        />
                    </Container>
                </BlogBoxReg>
            </BlogSection>

            <BlogSection>
                <BlogBoxReg title="Conclusion">
                    <BlogBox
                        className="max-sm:text-center"
                        content={`In a platform where visuals and captions matter immensely, the Instagram Post Generator provides the perfect blend of creativity, trend alignment, and SEO-friendly content. It empowers you to create posts that not only look good but also perform well, driving engagement and growing your online presence.`}
                    />
                </BlogBoxReg>
            </BlogSection>

            <BlogSection className="max-sm:text-center flex flex-col">
                <BlogContainer className="text-center mt-5">
                    <Link
                        href={handleLink('instagram-post-generator')}
                        target="_blank"
                        className="underline underline-offset-8 text-blue-400">
                        Instagram Post Generator
                    </Link>
                </BlogContainer>
            </BlogSection>
        </Blog>
    )
}
